#%RAML 1.0 Library
usage:
traits:
  transcationId: !include /libraries/common/traits/header-TranscationId-Traits.raml
  companyName: !include /libraries/common/traits/queryParams-companyName-trait.raml
  departureLocation: !include /libraries/common/traits/queryParams-departureLocationtrait.raml
  destinationLocation: !include /libraries/common/traits/queryParams-destinationLocation-trait.raml
  requestTimeZone: !include /libraries/common/traits/queryParams-requestTimeZoneTraits.raml